# Generated by Django 5.2.4 on 2025-07-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='glossary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
