# Generated by Django 5.2.4 on 2025-07-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_glossary'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='quiz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
