# Generated by Django 5.2.4 on 2025-07-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
