# Generated by Django 5.2.4 on 2025-07-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_studytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytask',
            name='tag',
            field=models.CharField(blank=True, choices=[('revision', 'Revision'), ('assignment', 'Assignment'), ('exam', 'Exam'), ('reading', 'Reading'), ('project', 'Project')], max_length=20, null=True),
        ),
    ]
